name: Portworx
description: |
  Volume plugin for Portworx Elastic Data Fabric, providing scale-out persistent storage for containers.
version: "1.3.4.0-oci"
category: Storage
labels:
  io.rancher.orchestration.supported: 'cattle'
